#!/bin/bash
# The following command can also be used standalone, although this script
# passes all arguments to Gunicorn. Most commonly, this is used to overwrite
# the log-file parameter.
# When calling Gunicorn from your own script and using Supervisord, be sure to
# use exec so you can stop and restart your Saltobserver instance.
exec uwsgi --master --logto saltobserver_uwsgi.log --http :8000 --http-websockets $@ --wsgi saltobserver:app
